### ISSUE TITLE
port is required

### ISSUE THREAD

**Issue by jdell64** [trailsjs/trails#149] opened 2016-04-18 14:42 UTC
#### Issue Description
I was running alpha-5, updated to beta-1

    Update available: 1.0.0-beta-1 (current: 1.0.0-alpha-5)

Created a new app `yo trails`:

```
Get ready to blaze a new Trails Application!

Checking for updates...
? Choose a Web Server hapi
? Choose an ORM waterline
? Do you want to use Footprints (automatic REST API from models) ? Yes
```

`npm start` gives me errors (added a line in sample_app/node_modules/trailpack-hapi/lib/validator.js for more visibility):

```
debug: trails event: trails:start

validateWebConfig value:{"plugins":[{"register":{},"options":{}},{"register":{},"options":{}}],"views":{"engines":{},"path":"views"}}

debug: trails event: trailpack:footprints:validated
debug: trails event: trailpack:repl:validated
debug: trails event: trailpack:core:validated
debug: trails event: trailpack:waterline:validated
debug: trails event: trailpack:router:validated
error: 
 TypeError: config.web: ValidationError: child "port" fails because ["port" is required]
    at /home/jeff/dev/trails/sample_app/node_modules/trailpack-hapi/lib/validator.js:11:32
    at internals.Any.applyFunctionToChildren.internals.Any._validateWithOptions (/home/jeff/dev/trails/sample_app/node_modules/trailpack-hapi/node_modules/joi/lib/any.js:648:16)
    at root.validate (/home/jeff/dev/trails/sample_app/node_modules/trailpack-hapi/node_modules/joi/lib/index.js:103:23)
    at /home/jeff/dev/trails/sample_app/node_modules/trailpack-hapi/lib/validator.js:8:11
    at Object.validateWebConfig (/home/jeff/dev/trails/sample_app/node_modules/trailpack-hapi/lib/validator.js:7:12)
    at Hapi.validate (/home/jeff/dev/trails/sample_app/node_modules/trailpack-hapi/index.js:27:21)
    at /home/jeff/dev/trails/sample_app/node_modules/trails/lib/trailpack.js:61:26
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:146:18)
    at node.js:404:3
error: 
```

#### Environment
- node version: 5.10.1
- trails version: 1.0.0-beta-1
- operating system: Linux Ubuntu x86_64

**Comment by jaumard** [comment] 2016-04-18 14:51
@jdell64 I reproduce the problem, you have to add `exports.web = require('./web')` under `config/index.js`
Thanks for the report.

**Comment by jdell64** [comment] 2016-04-18 15:01
Yes, but I'll also add that it doesn't look like the `web.js` file is generated either. In addition to that `exports` line, you may want to check that as well.

**Comment by jaumard** [comment] 2016-04-18 15:03
I just make the test and web.js was present I just add it to index.js and all works. I will check this.

**Comment by nimir** [comment] 2016-04-19 07:00
Same here, `config/web.js` was not generated by yeoman.

###Environment
- Node v: 4.4.3
- Trails v: 1.0.0-beta-1
- Operating System: Ubuntu 14.04 64

**Comment by jdell64** [comment] 2016-04-19 13:35
@nimir do this for a work around:

1. create `config/web.js` with the following content:

```
/**
 * Server Configuration
 * (app.config.web)
 *
 * Configure the Web Server
 *
 * @see {@link http://trailsjs.io/doc/config/web}
 */
module.exports = {

  /**
   * The port to bind the web server to
   */
  port: process.env.PORT || 3000
}
```
2. Add the following line to `config/index.js`:
```
exports.web = require('./web')
```

**Comment by nimir** [comment] 2016-04-20 06:37
thanks for the work around @jdell64 yes did that by comparing to https://github.com/trailsjs/trails-example-app and everything went smooth from there :smiley: 

I hope i am not stepping out of my limits but this bug as simple as it looks is very critical since a newbie to trails will get disappointed when he/she follows steps and gets an error running the server!

I am very new to trails but tried to dig see where this is coming from and my guess that #76 is somehow related! not sure though

**Comment by tjwebb** [comment] 2016-04-20 19:41
@nimir thanks for researching this. We've been pushing a lot of updates to the beta versions in preparation for a 1.0 release by the end of the month, and it looks like some versions are out of sync. I will look into this and make sure it gets resolved today.

**Comment by kvindasAB** [comment] 2016-04-23 05:05
+1.
Reproduced the issue on Mac ElCapitan, Node v4.4.3, Trails 1.0.0-beta-8

**Comment by jaumard** [comment] 2016-04-27 19:21
Normally this is fixed now :)

**Comment by jaumard** [comment] 2016-05-18 21:38
@wbprice this can be close

**Closed** 2016-05-19 00:33 UTC
Labels: bug
